import React from "react"
const User =[
        {
            username:'notyou',
            password:"thisisnotyoupassword",
            date: Date.now(),
            CartCode:"GTf752",
            confirm:"GJh6235",
            id:1,
        },
        {
            username:'notyou',
            password:"thisisnotyoupassword",
            date: Date.now(),
            CartCode:"GTf752",
            confirm:"GJh6235",
            id:2,
        },
        {
            username:'notyou',
            password:"thisisnotyoupassword",
            date: Date.now(),
            CartCode:"GTf752",
            confirm:"GJh6235",
            id:3,
        },
        {
            username:'notyou',
            password:"thisisnotyoupassword",
            date: Date.now(),
            CartCode:"GTf752",
            confirm:"GJh6235",
            id:4,
        },
        {
            username:'notyou',
            password:"thisisnotyoupassword",
            date: Date.now(),
            CartCode:"GTf752",
            confirm:"GJh6235",
            id:5,
        },
        {
            username:'notyou',
            password:"thisisnotyoupassword",
            date: Date.now(),
            CartCode:"GTf752",
            confirm:"GJh6235",
            id:6,
        },
        {
            username:'notyou',
            password:"thisisnotyoupassword",
            date: Date.now(),
            CartCode:"GTf752",
            confirm:"GJh6235",
            id:7,
        },
        {
            username:'notyou',
            password:"thisisnotyoupassword",
            date: Date.now(),
            CartCode:"GTf752",
            confirm:"GJh6235",
            id:8,
        },
        {
            username:'notyou',
            password:"thisisnotyoupassword",
            date: Date.now(),
            CartCode:"GTf752",
            confirm:"GJh6235",
            id:9,
        },
        {
            username:'notyou',
            password:"thisisnotyoupassword",
            date: Date.now(),
            CartCode:"GTf752",
            confirm:"GJh6235",
            id:10,
        },
        {
            username:'notyou',
            password:"thisisnotyoupassword",
            date: Date.now(),
            CartCode:"GTf752",
            confirm:"GJh6235",
            id:11,
        },

]

export default User